package KieRule;
import com.shiva.org.drools.model.Order;

rule "2 - HDFC only"

    when
        $o: org.drools.model.Order(cardType =="HDFC");
    then
        modify($o){
            setPrice(50000000);
        };
    end

rule "2 - HDFC and price greater than 10000"

    when
        $o: org.drools.model.Order(cardType =="HDFC" && price > 10000);
    then

        modify($o){
            setDiscount(10);
        }
    end