package drools.rules;

import org.drools.Order;
import org.drools.Customer;


rule "Classify Customer by order size greater than 5"
    when
        $o: Order( products.size >= 5, $customer: customer ) and
        $c: Customer(this == $customer, category == Customer.Category.NA)
    then
        modify($c){ 
		    setCategory(Customer.Category.GOLD)
	    };
end 

rule "Gold Customers - 10% Discount"
    when
        $o: Order($customer: customer )
        $c: Customer( category == Category.GOLD, this == $customer )
    then
        $o.setDiscount(10);
        update($o);
end