package drools.rules;

import org.drools.model.Order;
import org.drools.model.Customer;
import org.drools.model.Coupon;

rule "Classify Customer by order size greater than 5"
    when
        $o: Order( products.size >= 5, $customer: customer ) and
        $c: Customer(this == $customer, category == Customer.Category.NA)
    then
        modify($c){ 
		    setCategory(Customer.Category.GOLD)
	    };
end 

rule "Gold Customers - 10% Discount"
    when
        $o: Order($customer: customer )
        $c: Customer( category == Customer.Category.GOLD, this == $customer )
    then
        $o.setDiscount(10);
        update($o);
end

rule "Create Coupons for Gold Customers"
    when
        $o: Order( $customer: customer )
        $c: Customer(this == $customer, category == Customer.Category.GOLD )
    then
        insert(new Coupon($c, $o, Coupon.CouponType.POINTS));
end