package drools.rules;

import org.drools.model.Order;
import org.drools.model.Customer;
import org.drools.model.Customer.Category;


rule "Premium Customers - 20% Discount"
    when
        $o: Order( $customer: customer)
        $c: Customer( category == Category.PREMIUM, this == $customer )
    then
        System.out.println("Executing Premium Customer 20% Discount Rule!");
        $o.setDiscount(20);
        update($o);
end